#!/usr/bin/env python

"""
This file tests basic matrix translations.

We test **all** types and the symmetric and general cases.


     If this is a python script (.py), it has been automatically generated by the 'generate_code.py' script.

"""
from cysparse.sparse.ll_mat import *
from cysparse.types.cysparse_types import *
import numpy as np

import unittest

import sys


def is_equal(A, B):
    if A.nrow != B.nrow or A.ncol != B.ncol:
        return False

    for i in xrange(A.nrow):
        for j in xrange(A.ncol):
            if A[i, j] != B[i, j]:
                return False

    return True


########################################################################################################################
# Tests
########################################################################################################################
class CySparseCommonOperationsMatrixTranslationsBaseTestCase(unittest.TestCase):
    def setUp(self):
        pass


class CySparseCommonOperationsMatrixTranslationsTestCase(CySparseCommonOperationsMatrixTranslationsBaseTestCase):
    """

    """
    def setUp(self):
        self.nbr_of_elements = 10
        self.nrow = 4
        self.ncol = 6

{% for index_type in index_list %}
  {% set outerloop = loop %}
  {% for element_type in type_list %}
        self.l_@outerloop.index@_@loop.index@ = NewLinearFillLLSparseMatrix(nrow=self.nrow, ncol=self.ncol, itype=@index_type|type2enum@, dtype=@element_type|type2enum@, row_wise=False)

        self.l_@outerloop.index@_@loop.index@_csc = self.l_@outerloop.index@_@loop.index@.to_csc()
        self.l_@outerloop.index@_@loop.index@_csr = self.l_@outerloop.index@_@loop.index@.to_csr()
  {% endfor %}
{% endfor %}


    def test_simple_equality_one_by_one(self):
{% for index_type in index_list %}
  {% set outerloop = loop %}
  {% for element_type in type_list %}
        self.failUnless(is_equal(self.l_@outerloop.index@_@loop.index@_csc.to_csr(), self.l_@outerloop.index@_@loop.index@_csr))
        self.failUnless(is_equal(self.l_@outerloop.index@_@loop.index@_csr.to_csc(), self.l_@outerloop.index@_@loop.index@_csc))
  {% endfor %}
{% endfor %}


class CySparseCommonOperationsSymMatrixTranslationsTestCase(CySparseCommonOperationsMatrixTranslationsBaseTestCase):
    """

    """
    def setUp(self):
        self.nbr_of_elements = 10
        self.nrow = 6
        self.ncol = 6

{% for index_type in index_list %}
  {% set outerloop = loop %}
  {% for element_type in type_list %}
        self.l_@outerloop.index@_@loop.index@ = NewLinearFillLLSparseMatrix(nrow=self.nrow, ncol=self.ncol, itype=@index_type|type2enum@, dtype=@element_type|type2enum@, is_symmetric=True, row_wise=False)

        self.l_@outerloop.index@_@loop.index@_csc = self.l_@outerloop.index@_@loop.index@.to_csc()
        self.l_@outerloop.index@_@loop.index@_csr = self.l_@outerloop.index@_@loop.index@.to_csr()
  {% endfor %}
{% endfor %}


    def test_simple_equality_one_by_one(self):
{% for index_type in index_list %}
  {% set outerloop = loop %}
  {% for element_type in type_list %}
        self.failUnless(is_equal(self.l_@outerloop.index@_@loop.index@_csc.to_csr(), self.l_@outerloop.index@_@loop.index@_csr))
        self.failUnless(is_equal(self.l_@outerloop.index@_@loop.index@_csr.to_csc(), self.l_@outerloop.index@_@loop.index@_csc))
  {% endfor %}
{% endfor %}


if __name__ == '__main__':
    unittest.main()