#!/usr/bin/env python

"""
This file tests basic diagonals retrievals.

We test **all** types and the symmetric and general cases.


     If this is a python script (.py), it has been automatically generated by the 'generate_code.py' script.

"""
from cysparse.sparse.ll_mat import *
from cysparse.types.cysparse_types import *
import numpy as np

import unittest

import sys


def is_equal(A, B):
    if A.size != B.size:
        return False

    for i in xrange(A.size):
        if A[i] != B[i]:
            return False

    return True

########################################################################################################################
# Tests
########################################################################################################################
class CySparseCommonOperationsDiagonalsBaseTestCase(unittest.TestCase):
    def setUp(self):
        pass


class CySparseCommonOperationsDiagonalsTestCase(CySparseCommonOperationsDiagonalsBaseTestCase):
    """

    """
    def setUp(self):
        self.nbr_of_elements = 24
        self.nrow = 4
        self.ncol = 6

{% for index_type in index_list %}
  {% set outerloop = loop %}
  {% for element_type in type_list %}
        self.l_@outerloop.index@_@loop.index@ = NewLinearFillLLSparseMatrix(nrow=self.nrow, ncol=self.ncol, itype=@index_type|type2enum@, dtype=@element_type|type2enum@, row_wise=False)

        self.l_@outerloop.index@_@loop.index@_csc = self.l_@outerloop.index@_@loop.index@.to_csc()
        self.l_@outerloop.index@_@loop.index@_csr = self.l_@outerloop.index@_@loop.index@.to_csr()
  {% endfor %}
{% endfor %}


    def test_simple_equality_one_by_one_negative_diagonals(self):
{% for index_type in index_list %}
  {% set outerloop = loop %}
  {% for element_type in type_list %}
        # negative diagonals
        for i in xrange(0, -self.nrow, -1):
            self.failUnless(is_equal(self.l_@outerloop.index@_@loop.index@_csc.diag(i), self.l_@outerloop.index@_@loop.index@_csr.diag(i)))
            self.failUnless(is_equal(self.l_@outerloop.index@_@loop.index@_csr.diag(i), self.l_@outerloop.index@_@loop.index@.diag(i)))
  {% endfor %}
{% endfor %}

    def test_simple_equality_one_by_one_positive_diagonals(self):
{% for index_type in index_list %}
  {% set outerloop = loop %}
  {% for element_type in type_list %}
        # negative diagonals
        for i in xrange(1, self.ncol):
            self.failUnless(is_equal(self.l_@outerloop.index@_@loop.index@_csc.diag(i), self.l_@outerloop.index@_@loop.index@_csr.diag(i)))
            self.failUnless(is_equal(self.l_@outerloop.index@_@loop.index@_csr.diag(i), self.l_@outerloop.index@_@loop.index@.diag(i)))
  {% endfor %}
{% endfor %}

class CySparseCommonOperationsSymDiagonalsTestCase(CySparseCommonOperationsDiagonalsBaseTestCase):
    """

    """
    def setUp(self):
        self.nbr_of_elements = 36
        self.nrow = 6
        self.ncol = 6

{% for index_type in index_list %}
  {% set outerloop = loop %}
  {% for element_type in type_list %}
        self.l_@outerloop.index@_@loop.index@ = NewLinearFillLLSparseMatrix(nrow=self.nrow, ncol=self.ncol, itype=@index_type|type2enum@, dtype=@element_type|type2enum@, is_symmetric=True, row_wise=False)

        self.l_@outerloop.index@_@loop.index@_csc = self.l_@outerloop.index@_@loop.index@.to_csc()
        self.l_@outerloop.index@_@loop.index@_csr = self.l_@outerloop.index@_@loop.index@.to_csr()
  {% endfor %}
{% endfor %}


    def test_simple_equality_one_by_one_negative_diagonals(self):
{% for index_type in index_list %}
  {% set outerloop = loop %}
  {% for element_type in type_list %}
        # negative diagonals
        for i in xrange(0, -self.nrow, -1):
            self.failUnless(is_equal(self.l_@outerloop.index@_@loop.index@_csc.diag(i), self.l_@outerloop.index@_@loop.index@_csr.diag(i)))
            self.failUnless(is_equal(self.l_@outerloop.index@_@loop.index@_csr.diag(i), self.l_@outerloop.index@_@loop.index@.diag(i)))
  {% endfor %}
{% endfor %}

    def test_simple_equality_one_by_one_positive_diagonals(self):
{% for index_type in index_list %}
  {% set outerloop = loop %}
  {% for element_type in type_list %}
        # negative diagonals
        for i in xrange(1, self.ncol):
            self.failUnless(is_equal(self.l_@outerloop.index@_@loop.index@_csc.diag(i), self.l_@outerloop.index@_@loop.index@_csr.diag(i)))
            self.failUnless(is_equal(self.l_@outerloop.index@_@loop.index@_csr.diag(i), self.l_@outerloop.index@_@loop.index@.diag(i)))
  {% endfor %}
{% endfor %}

if __name__ == '__main__':
    unittest.main()